org: jmlamodiere
app: aws-node-project
service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-3
  profile: ${self:custom.profiles.${sls:stage}}

custom:
  profiles:
    dev: jm-dev

functions:
  hello:
    handler: handler.hello
